theme: jekyll-theme-slate
title: This is the homepage of cara, a cute dog.
description: What you will find here are links to projects, publications, and repositories related to the former. Expect some delay in reporting!
plugins:
  - jemoji
url: "https://caraZ02.github.io/"
markdown: kramdown