remote_theme: pages-themes/merlot@v0.2.0
title: This is the homepage of Cara, a cute dog.
description: What you will find here are everything about Cara such as age,breed,hobbies,pictures etc. 
plugins:
  - jekyll-remote-theme
url: "https://caraZ02.github.io/"
markdown: kramdown